import { describe, expect, it } from 'vitest';

import { bondRecipient, isStakeRecipient, withdrawBondRecipient } from './stake';
import recipients from './stake-recipients.json';

/**
 * Pinned to the node's own spelling by generated vectors.
 *
 * A recipient string is not validated against a list - it is PARSED, and a
 * prefix that differs by one character produces a transfer to an ordinary
 * account whose name happens to look like an operation. That does not fail: the
 * money moves, to an account nobody holds a key for. So the strings are
 * generated by the Go implementation rather than typed here from memory.
 */

interface Vector {
  account: string;
  bond: string;
  withdraw: string;
}

const vectors = recipients as unknown as Vector[];

describe('stake recipients match the node', () => {
  it('has vectors to check against', () => {
    expect(vectors.length).toBeGreaterThan(0);
  });

  for (const v of vectors) {
    it(`spells them the same way: ${v.account}`, () => {
      expect(bondRecipient(v.account)).toBe(v.bond);
      expect(withdrawBondRecipient(v.account)).toBe(v.withdraw);
    });
  }

  it('recognises a stake recipient, and does not mistake an account for one', () => {
    expect(isStakeRecipient(bondRecipient('eth:0xabc'))).toBe(true);
    expect(isStakeRecipient('eth:0xabc')).toBe(false);
    expect(isStakeRecipient('consensus/stake')).toBe(false);
  });
});
